[package]
name = "mk20d7"
version = "0.1.0"
authors = ["Jacob Hughes <j@jacobhughes.me>"]

[dependencies]
bare-metal = "0.1"
vcell = "0.1"
cortex-m = "0.4"

[dependencies.cortex-m-rt]
optional = true
version = "0.3"

[features]
rt = ["cortex-m-rt"]
